### ISSUE TITLE
Publish the scalyr-logback artifact to Maven Central

### ISSUE THREAD

**Issue by tburch** [scalyr/scalyr-logback#3]
It'd be really nice to be able to have the `scalyr-logback` jar available in [Maven Central](http://mvnrepository.com). This way I can just have it as a dependency in my project instead of having to download and include the jar in my source.

**Comment by soboko** [comment]
Hi, 

We finally mavenized the project and got it into Maven Central (though we took a slightly different approach than the one in your pull request).

I decided not to include transitive dependencies for a couple of reasons, but other than that, the end result is fairly similar to what's in your pull request.

If you're still interested, check out the instructions at https://github.com/scalyr/scalyr-logback and please let me know if you have any comments.

Thanks!
Chris
